version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwertyuiop
      MYSQL_DATABASE: geoquiz_mobile
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: qweasdzxc
    ports:
      - "3306:3306"
    volumes:
      - dev_mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    container_name: dev_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwertyuiop
      MONGO_INITDB_DATABASE: geoquiz_mobile
    ports:
      - "27017:27017"
    volumes:
      - dev_mongodb_data:/data/db

volumes:
  dev_mysql_data:
  dev_mongodb_data: