// <auto-generated />
using System;
using GeoQuiz_backend.Infrastructure.Persistence.MySQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoQuiz_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417132310_UpdateQuestionSet")]
    partial class UpdateQuestionSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("KothMatchId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int?>("Place")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PvPMatchId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("RoundsSurvived")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("KothMatchId");

                    b.HasIndex("PvPMatchId");

                    b.HasIndex("UserId");

                    b.ToTable("gamesessions", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.KothAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("ScoreGained")
                        .HasColumnType("int");

                    b.Property<int>("TimeSpentMs")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MatchId", "RoundNumber");

                    b.ToTable("kothanswers", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.KothMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("CurrentRoundType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SelectedMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("kothmatches", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.KothPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Place")
                        .HasColumnType("int");

                    b.Property<int>("RoundEliminated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MatchId", "UserId")
                        .IsUnique();

                    b.ToTable("kothplayers", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.ModeDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvailableModes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BannedModes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CurrentTurnUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PvPMatchId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PvPMatchId")
                        .IsUnique();

                    b.ToTable("modedraft", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.PvPAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ScoreGained")
                        .HasColumnType("int");

                    b.Property<int>("TimeSpentMs")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("pvpanswers", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.PvPMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Player2Id")
                        .HasColumnType("char(36)");

                    b.Property<int?>("SelectedMode")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("pvpmatches", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.QuestionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("KothMatchId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<Guid?>("PvPMatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("QuestionIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Regions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KothMatchId");

                    b.HasIndex("PvPMatchId")
                        .IsUnique();

                    b.ToTable("questionset", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("userachievements", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.UserStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("AfricaCorrect")
                        .HasColumnType("int");

                    b.Property<int>("AmericaCorrect")
                        .HasColumnType("int");

                    b.Property<int>("AsiaCorrect")
                        .HasColumnType("int");

                    b.Property<int>("CapitalsCorrect")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPvPStreak")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWinStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DailyLoginStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EuropeCorrect")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("FlagsCorrect")
                        .HasColumnType("int");

                    b.Property<int>("KothGamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KothGamesWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KothTop3Finishes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("LanguagesCorrect")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAchievementSync")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("MaxWinStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("OceaniaCorrect")
                        .HasColumnType("int");

                    b.Property<int>("OutlinesCorrect")
                        .HasColumnType("int");

                    b.Property<int>("PvPGamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("PvPGamesWon")
                        .HasColumnType("int");

                    b.Property<int>("TotalCorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TotalGamesWon")
                        .HasColumnType("int");

                    b.Property<int>("TotalLastSecondWins")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuickAnswers")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("userstats", (string)null);
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.KothMatch", "KothMatch")
                        .WithMany()
                        .HasForeignKey("KothMatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoQuiz_backend.Domain.Entities.PvPMatch", "PvPMatch")
                        .WithMany()
                        .HasForeignKey("PvPMatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KothMatch");

                    b.Navigation("PvPMatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.KothAnswer", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.KothMatch", "Match")
                        .WithMany("Answers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.KothMatch", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.KothPlayer", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.KothMatch", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.ModeDraft", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.PvPMatch", "PvPMatch")
                        .WithOne("Draft")
                        .HasForeignKey("GeoQuiz_backend.Domain.Entities.ModeDraft", "PvPMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PvPMatch");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.PvPAnswer", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.PvPMatch", "Match")
                        .WithMany("Answers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "User")
                        .WithMany("PvPAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.PvPMatch", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.QuestionSet", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.KothMatch", "KothMatch")
                        .WithOne("QuestionSet")
                        .HasForeignKey("GeoQuiz_backend.Domain.Entities.QuestionSet", "KothMatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeoQuiz_backend.Domain.Entities.PvPMatch", "PvPMatch")
                        .WithOne("QuestionSet")
                        .HasForeignKey("GeoQuiz_backend.Domain.Entities.QuestionSet", "PvPMatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KothMatch");

                    b.Navigation("PvPMatch");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("GeoQuiz_backend.Domain.Entities.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.UserStats", b =>
                {
                    b.HasOne("GeoQuiz_backend.Domain.Entities.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("GeoQuiz_backend.Domain.Entities.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.KothMatch", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Players");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.PvPMatch", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Draft");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("GeoQuiz_backend.Domain.Entities.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("PvPAnswers");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
